import './style.css'
import './globals.css'
import { Roboto } from 'next/font/google'

import Header from './components/Header';

const roboto = Roboto({ weight: ['300', '400', '500', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true} >
        <Header />
        <main className='container mx-auto px-4 pt-[100px]'>
          {children}
        </main>
      </body>
    </html>
  )
}
